# Copyright (c) Microsoft Corporation. Licensed under the MIT License.
name: Dependency Review
on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/dependency-review-action@da24556b548a50705dd671f47852072ea4c105d9 # v4.7.1
        with:
          fail-on-severity: moderate
          comment-summary-in-pr: always
          allow-licenses: >
            MIT, Apache-2.0, BSD-2-Clause, BSD-3-Clause, ISC,
            PSF-2.0, Python-2.0, 0BSD, Unlicense, CC0-1.0,
            CC-BY-4.0, Zlib, BSL-1.0, MPL-2.0
